plugins { id 'com.android.application' }

android {
    namespace 'com.turrinistudio.gtav'
    compileSdk 35

    defaultConfig {
        applicationId 'com.turrinistudio.gtav'
        minSdk 24
        targetSdk 35
        versionCode 60
        versionName '6.0-REALISTIC'
        ndk { abiFilters 'arm64-v8a' }
        externalNativeBuild {
            cmake {
                cppFlags '-std=c++17 -O2 -ffast-math -fexceptions -frtti'
                arguments '-DANDROID_STL=c++_shared'
            }
        }
    }

    externalNativeBuild {
        cmake { path 'src/main/cpp/CMakeLists.txt'; version '3.22.1' }
    }

    packaging {
        jniLibs.useLegacyPackaging = true
    }
}
